/**
 * Disposable local test database (isolated PGLite + demo seed data).
 *
 * Usage:
 *   pnpm run test:db:create    — create sandbox + seed demo accounts
 *   pnpm run test:db:dev       — run API + web against the sandbox
 *   pnpm run test:db:reset     — re-seed demo data (keeps sandbox folder)
 *   pnpm run test:db:destroy   — delete sandbox (prompts for confirmation)
 *   pnpm run test:db:destroy -- --yes   — delete without prompting
 */
import { createRequire } from "node:module";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import readline from "node:readline/promises";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sandboxRoot = path.join(repoRoot, ".data", "test-sandbox");
const sandboxPglite = path.join(sandboxRoot, "pglite");
const sandboxEnvPath = path.join(repoRoot, ".env.test-sandbox");
const seedJsonPath = path.join(repoRoot, "lib", "sync-store", "seed", "prototype-seed.json");
const metaPath = path.join(sandboxRoot, "meta.json");

const PASSTHROUGH_ENV_KEYS = [
  "VITE_SUPABASE_URL",
  "VITE_SUPABASE_ANON_KEY",
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "VITE_API_URL",
  "VITE_ADMIN_PHONES",
  "ADMIN_PHONES",
  "VITE_GOOGLE_MAPS_API_KEY",
  "RESEND_API_KEY",
  "FEEDBACK_FROM_EMAIL",
  "FEEDBACK_NOTIFY_EMAIL",
  "GEMINI_API_KEY",
];

function parseEnvFile(filePath) {
  if (!existsSync(filePath)) return {};
  const out = {};
  for (const line of readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    out[key] = value;
  }
  return out;
}

function formatEnvFile(entries) {
  const lines = [
    "# Generated by pnpm run test:db:create — safe to delete with pnpm run test:db:destroy",
    "# Isolated fake DB for local testing; does not touch .data/pglite or staging.",
    "",
  ];
  for (const [key, value] of Object.entries(entries)) {
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  return lines.join("\n");
}

function loadPglite() {
  const require = createRequire(path.join(repoRoot, "lib", "db", "package.json"));
  const { PGlite } = require("@electric-sql/pglite");
  return PGlite;
}

async function initSchema(dataDir) {
  const PGlite = loadPglite();
  const DDL = `
CREATE TABLE IF NOT EXISTS "user_data" (
  "phone" text NOT NULL,
  "role" text NOT NULL,
  "data_key" text NOT NULL,
  "value" text NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "user_data_phone_role_data_key_pk" PRIMARY KEY("phone","role","data_key")
);
ALTER TABLE "user_data" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.tenant_invitations (
  id text PRIMARY KEY,
  token text NOT NULL UNIQUE,
  owner_phone text NOT NULL,
  owner_name text NOT NULL,
  property_id text NOT NULL,
  property_label text NOT NULL,
  tenant_name text NOT NULL,
  tenant_phone text NOT NULL,
  monthly_rent text NOT NULL DEFAULT '',
  maintenance_included boolean NOT NULL DEFAULT false,
  monthly_maintenance text NOT NULL DEFAULT '',
  security_deposit text NOT NULL DEFAULT '',
  start_date text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'declined', 'expired')),
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  declined_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tenant_invitations_owner_phone_idx
  ON public.tenant_invitations (owner_phone);
CREATE INDEX IF NOT EXISTS tenant_invitations_token_idx
  ON public.tenant_invitations (token);
`;
  const client = new PGlite(dataDir);
  await client.exec(DDL);
  await client.close();
}

async function seedPrototypeAccounts(dataDir) {
  const PGlite = loadPglite();
  const seed = JSON.parse(readFileSync(seedJsonPath, "utf8"));
  const client = new PGlite(dataDir);

  for (const [accountKey, data] of Object.entries(seed)) {
    const [phone, role] = accountKey.split(":");
    if (!phone || !role) continue;
    for (const [dataKey, value] of Object.entries(data)) {
      await client.query(
        `INSERT INTO user_data (phone, role, data_key, value, updated_at)
         VALUES ($1, $2, $3, $4, NOW())
         ON CONFLICT (phone, role, data_key)
         DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()`,
        [phone, role, dataKey, value],
      );
    }
  }

  await client.close();
}

function writeSandboxEnv() {
  const baseEnv = parseEnvFile(path.join(repoRoot, ".env"));
  const entries = {};

  for (const key of PASSTHROUGH_ENV_KEYS) {
    if (baseEnv[key]) entries[key] = baseEnv[key];
  }

  Object.assign(entries, {
    DATABASE_URL: "local",
    PGLITE_DATA_DIR: sandboxPglite.replace(/\\/g, "/"),
    USE_MOCK_DB: "0",
    SYNC_AUTH_DISABLED: "1",
    API_PORT: baseEnv.API_PORT ?? "8080",
    WEB_PORT: baseEnv.WEB_PORT ?? "5173",
    PORT: baseEnv.PORT ?? baseEnv.API_PORT ?? "8080",
  });

  writeFileSync(sandboxEnvPath, formatEnvFile(entries), "utf8");
}

function writeMeta() {
  const meta = {
    createdAt: new Date().toISOString(),
    pgliteDir: sandboxPglite,
    demoAccounts: [
      { role: "owner", phone: "9876543210", name: "Demo Owner" },
      { role: "broker", phone: "9876543211", name: "Demo Broker" },
    ],
  };
  writeFileSync(metaPath, JSON.stringify(meta, null, 2), "utf8");
}

function printSandboxInfo() {
  console.log("");
  console.log("Test sandbox is ready (isolated from .data/pglite and staging).");
  console.log("");
  console.log("Demo accounts:");
  console.log("  Owner  — phone 9876543210  (Demo Owner)");
  console.log("  Broker — phone 9876543211  (Demo Broker)");
  console.log("");
  console.log("Data path:", sandboxPglite);
  console.log("Env file:", sandboxEnvPath);
  console.log("");
  console.log("Start dev stack:  pnpm run test:db:dev");
  console.log("Seed onboard link: pnpm run test:db:seed-onboard");
  console.log("Delete sandbox:    pnpm run test:db:destroy");
  console.log("");
  console.log("Tip: SYNC_AUTH_DISABLED=1 is set so broker onboard APIs work without Supabase JWT.");
  console.log("     Copy Supabase keys from .env for OTP login, or sign up with any 4-digit OTP in dev.");
  console.log("");
}

async function cmdCreate() {
  mkdirSync(sandboxRoot, { recursive: true });
  mkdirSync(sandboxPglite, { recursive: true });

  const fileStoreCopy = path.join(sandboxRoot, "user_data.json");
  copyFileSync(seedJsonPath, fileStoreCopy);

  await initSchema(sandboxPglite);
  await seedPrototypeAccounts(sandboxPglite);
  writeSandboxEnv();
  writeMeta();
  printSandboxInfo();
}

async function cmdReset() {
  if (!existsSync(sandboxPglite)) {
    console.error("No sandbox found. Run: pnpm run test:db:create");
    process.exit(1);
  }
  await seedPrototypeAccounts(sandboxPglite);
  copyFileSync(seedJsonPath, path.join(sandboxRoot, "user_data.json"));
  console.log("Test sandbox data reset to prototype seed.");
  printSandboxInfo();
}

async function cmdDestroy(force) {
  if (!existsSync(sandboxRoot) && !existsSync(sandboxEnvPath)) {
    console.log("No test sandbox to delete.");
    return;
  }

  if (!force) {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const answer = (await rl.question("Delete test sandbox and .env.test-sandbox? [y/N] ")).trim();
    rl.close();
    if (answer.toLowerCase() !== "y" && answer.toLowerCase() !== "yes") {
      console.log("Cancelled.");
      return;
    }
  }

  if (existsSync(sandboxRoot)) {
    rmSync(sandboxRoot, { recursive: true, force: true });
  }
  if (existsSync(sandboxEnvPath)) {
    rmSync(sandboxEnvPath, { force: true });
  }

  console.log("Test sandbox deleted.");
}

function cmdInfo() {
  if (!existsSync(metaPath)) {
    console.log("No test sandbox found. Run: pnpm run test:db:create");
    process.exit(1);
  }
  printSandboxInfo();
  console.log(readFileSync(metaPath, "utf8"));
}

const [command, ...args] = process.argv.slice(2);
const forceDestroy = args.includes("--yes") || args.includes("-y");

switch (command) {
  case "create":
    await cmdCreate();
    break;
  case "reset":
    await cmdReset();
    break;
  case "destroy":
    await cmdDestroy(forceDestroy);
    break;
  case "info":
    cmdInfo();
    break;
  default:
    console.error("Usage: node scripts/test-sandbox.mjs <create|destroy|reset|info> [--yes]");
    process.exit(1);
}
